### ISSUE TITLE
Not working with  port 443 only with port 80

### ISSUE THREAD

**Issue by normed** [8gears/containerized-guacamole#1]
Hi , 
Maybe i am wrong and i  missed something .
here is my env file 
POSTGRES_USER=guacadb
POSTGRES_PASSWORD=Mypassword
# Uncomment if you want to test with dummy certificates
#LETSENCRYPT_TEST=false
VIRTUAL_HOST= mydomain
LETSENCRYPT_HOST=Mydomain
LETSENCRYPT_EMAIL=Mymail

When i followed the process  it only work with port 80 .  I edited the nginx conf file and i saw that nginx is listening on port 80 not 443. I changed the port and then it worked

**Comment by Vad1mo** [comment]
Where did you change the port, from what to what. Can you provide some more context?
Can you paste some logs?


guac itself is listening on the unsecure port 4822. NGINX is doing the TLS. So you service should only be available on TLS, as there is an HTTP to HTTPS redirection.

**Comment by normed** [comment]
Hi Vadim, 
I  stopped the containers , kill them and relaunch the two docker-compose   and  it works like a charm.
Sorry  for  my mistakes . ( previously in the nginx container i did a netstat  and i didn’t see  that is listening on the port 443 , maybe i need  a new pair of glasses :) 
I should have checked again and again. Sorry for the convenience.
Just to say that  you did a great job.
regards

**Comment by normed** [comment]
Hi 
I know  where was my mistake.
When i launch the compose  i went unto the nginx container and i had the following  display 




No  listening on port 443 .



I restarted the nginx container and  this time i had the nginx listening on port 443 




Regards
