### ISSUE TITLE
show remote host ip behind reverse proxy

### ISSUE THREAD

**Issue by paxprot** [8gears/containerized-guacamole#11]
This setup shows nginx's ip as remote host ip, is there a way to show the real ip behind reverse proxy?

**Comment by Vad1mo** [comment]
I guess you should take a look at the [Nginx PROXY Protocol](https://docs.nginx.com/nginx/admin-guide/load-balancer/using-proxy-protocol/) and how this can be set in https://github.com/nginx-proxy/

e.g. https://github.com/nginx-proxy/nginx-proxy/pull/1487 and https://github.com/nginx-proxy/nginx-proxy/discussions/1621

**Comment by paxprot** [comment]
Thank you for your reply. I haven't tested whether changing nginx config would work, but I managed to add remote ip valve to the tomcat config inside the guacamole container, and it seems to resolve the problem.
