### ISSUE TITLE
remove /guacamole/

### ISSUE THREAD

**Issue by theoneandonly-vector** [8gears/containerized-guacamole#4]
hey there

as there is only guacamole running on this docker.compose I think it would make sense to run directly @root.

**Comment by Vad1mo** [comment]
Why

**Comment by theoneandonly-vector** [comment]
because it's easier to access it when I only need to type the name of my
service without /guacamole on a new device.
I would say it's quite standard to deploy something on the root dir "/"
when you only havw one service running.

Vadim Bauer ***@***.***> schrieb am Do., 2. Sept. 2021, 21:08:

**Comment by Vad1mo** [comment]
yeah would be nice, but jwilder/nginx-proxy does not support that. We would need to do some major configuration which would make the project not so simple to use.

You are free to make customization as needed and provide a PR.

**Comment by theoneandonly-vector** [comment]
I think this should be possible by manipulating the "proxy_pass" -variable of the nginx config. maybe you know hoe to do this without modifying the containers?

**Comment by Vad1mo** [comment]
Give it a try. If it stays simple, I'll merge it ASAP.

**Comment by theoneandonly-vector** [comment]
@Vad1mo 
hey there
this should be possible by just renaming guacamole.war -> ROOT.war!
