### ISSUE TITLE
PostgreSQL image needs to stay at 9.6

### ISSUE THREAD

**Issue by jcsogo** [8gears/containerized-guacamole#5]
First of all, many thanks for this repository. It is plain and simply wonderful.

I had though an issue when trying to deploy a new system. I was getting an authentication error in PostgreSQL. In order to solve this I had to make the postgresql container to stick to version 9.6 and recreate the database from the init step.

**Comment by theoneandonly-vector** [comment]
@Vad1mo I get this error:
```
The data directory was initialized by PostgreSQL version 13, which is not compatible with this version 14.0 (Debian 14.0-1.pgdg110+1)
```

**Comment by Vad1mo** [comment]
@theoneandonly-vector modify the compose file and set postgres to 13

`image: postgres:13`

https://github.com/8gears/containerized-guacamole/blob/master/docker-compose.yml#L44

**Comment by theoneandonly-vector** [comment]
yes, I did this.
but now I should export the data, updte to psql to v14 and then import, right?

**Comment by Vad1mo** [comment]
Keep using 13 there is no need to upgrade to 14. 

If you still want to upgrade see the Postgres upgrade guide for more details and a step by step guide .
