### ISSUE TITLE
initdb script failing

### ISSUE THREAD

**Issue by mlchai** [8gears/containerized-guacamole#8]
Following the directions, running the initdb container alone gets this output:

```
Creating network "containerized-guacamole_default" with the default driver
Creating volume "containerized-guacamole_dbinit" with default driver
Creating volume "containerized-guacamole_dbdata" with default driver
Creating containerized-guacamole_init-guac-db_1 ... done
Attaching to containerized-guacamole_init-guac-db_1
init-guac-db_1       | /bin/sh: 1: cannot create /init/initdb.sql: Permission denied
containerized-guacamole_init-guac-db_1 exited with code 2
```

I looked into the docker-compose file and found that although there's a POSTGRES_PASSWORD env var in .env, it doesn't seem to be used in the docker-compose file. Not sure what else could be causing this issue.

**Comment by Vad1mo** [comment]
is it maybe related to the compose eg. https://stackoverflow.com/questions/48495663/docker-compose-env-file-not-working

**Comment by Vad1mo** [comment]
let me know if you found a solution, so we can better document it or change the code

**Comment by johnmacfadyen** [comment]
The script is running with the UID/GID of the container user. So you need to make sure that the permissions on your docker volume match or it can't write to the directory. 
I ended up chowning my docker volumes to match the correct uid.

**Comment by qvqn** [comment]
i did this 

#get your id
$ id

#update .env with the id usng root as example
 UID=0
 GID=0

#update docker compose files with id
 init-guac-db: 
     user: "${UID}:${GID}"

**Comment by mlchai** [comment]
I see, thanks. This only works for bound/mounted volumes and not named volumes though, right?

**Comment by mlchai** [comment]
> i did this
> 
> #get your id $ id
> 
> #update .env with the id usng root as example UID=0 GID=0
> 
> #update docker compose files with id init-guac-db: user: "${UID}:${GID}"

Sadly I tried this and it didn't work, but it seems like something along these lines is the right move.

**Comment by qvqn** [comment]
what is your 

ls -l /var/lib/docker/volumes

**Comment by johnmacfadyen** [comment]
> > The script is running with the UID/GID of the container user. So you need to make sure that the permissions on your docker volume match or it can't write to the directory. I ended up chowning my docker volumes to match the correct uid.
> 
> I see, thanks. This only works for bound/mounted volumes and not named volumes though, right?

The named volumes are stored in /var/lib/docker/volumes
So in my case I was lazier than @qvqn and did a chown john:john /var/lib/docker/volumes/guacamole_* -R

**Comment by mlchai** [comment]
> ls -l /var/lib/docker/volumes

Tells me permission denied.

**Comment by mlchai** [comment]
> 

Ah I see, thanks! I'll give that a shot.

**Comment by mlchai** [comment]
Just an update, was able to get this to work without doing anything manual by doing the following:

- add `user: 0:0` to `init-guac-db` as recommended by @qvqn 
- mount the dbinit volume to an actual folder on the host instead of a docker volume

Gonna close this issue now, thanks everyone!
