### ISSUE TITLE
re-initialize nginx / ssl after domain-change

### ISSUE THREAD

**Issue by theoneandonly-vector** [8gears/containerized-guacamole#9]
hey there
I had to move away from my .tk domain. now I don't want to lose my guacamole-config and just rewrote the domain inside .env

but when I restart docker-compose it will provide me with a temporary cert and shows "503 Service Temporarily Unavailable"

is there a way to just re-initialize the nginx-part?

**Comment by Vad1mo** [comment]
Maybe you need to check the tomcat part as the old domain might be there.  check the guacamole docs. 

let me know if you fund a solution, i ll add it to the docs then

**Comment by theoneandonly-vector** [comment]
I was looking around in the docker container while it's running a bit.. and I think it's not Tomcats part.
what I can see is that in nginx container there is only the old cert-folder and inside "default.conf" there's only the old domain name too.. 
so I really think re-initializing the nginx-part would fix this..
but I dont' know what would eb the best way to do that.

**Comment by theoneandonly-vector** [comment]
alright.. just had not enough space. so changing .env and default.conf is enough :)
